export const data: any = [
  {
    employer_name: "Logic20/20, Inc.",
    employer_logo:
      "https://media.licdn.com/dms/image/D560BAQEovQVnyz6Ewg/company-logo_200_200/0/1690416645217/logic20_20_inc__logo?e=2147483647&v=beta&t=VxQ6Bik1MZSk3k0QkZY9ybLhl7d5E_uyireGVCObcW0",
    employer_website: "http://www.logic2020.com",
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "LmA80Ixex5j6B_DCAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "JavaScript Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/javascript-developer-at-logic20-20-inc-3756106360",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6737,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/javascript-developer-at-logic20-20-inc-3756106360",
        is_direct: false,
      },
      {
        publisher: "Indeed",
        apply_link: "https://www.indeed.com/viewjob?jk=93bd10e00ee41d9c",
        is_direct: false,
      },
      {
        publisher: "Talent.com",
        apply_link: "https://www.talent.com/view?id=5933fa6bbe32",
        is_direct: false,
      },
      {
        publisher: "Monster",
        apply_link:
          "https://www.monster.com/job-openings/javascript-developer-austin-tx--a5240b11-2b8b-44e2-86a1-720dd0105ec5",
        is_direct: false,
      },
      {
        publisher: "CareerBuilder",
        apply_link: "https://www.careerbuilder.com/job/J3M7816BJ1H45JKC3H6",
        is_direct: false,
      },
      {
        publisher: "Ladders",
        apply_link:
          "https://www.theladders.com/job-listing/senior-ui-developer-logic20-20-inc-austin-texas-_v2_-11-3264572719.html",
        is_direct: false,
      },
      {
        publisher: "Resume-Library.com",
        apply_link:
          "https://www.resume-library.com/job/view/128721197/senior-ui-developer",
        is_direct: true,
      },
      {
        publisher: "Trabajo.org",
        apply_link:
          "https://us.trabajo.org/job-524-20231027-408b0d96c199d7e99c8aed7e7af8ad03",
        is_direct: false,
      },
    ],
    job_description:
      "Company Description\n\nLogic20/20 invests in being a “Best Company to Work For,” where talented people come together to deliver exceptional solutions. We bring clarity, insights, and optimization to enterprise organizations spanning technology, telecommunications, utilities, healthcare, and more.\n\nWe thrive as One Team, built on values:\n• We Foster a Culture of We by prioritizing connection and collaboration.\n• We Drive toward Excellence by investing in professional growth and cultivating thought leadership.\n• We Act with Integrity by doing the right thing and bringing our best selves to the table.\n\nTo make it all possible, we’ve created programs, resources, and benefits that promote connection and help you evolve your career.\n\nJob Description\n\nAs a JavaScript Developer, you’ll be responsible for all aspects of the software development lifecycle, which includes estimating, technical design, implementation, documentation, testing, deployment, and support of innovative applications developed for our clients. You will team with solution architects and developers on the translation of wireframes and creative designs into functional requirements, and subsequently into technical design.\n\nAbout The Team\n\nThe Logic20/20 Digital Transformation team applies design thinking and next-gen technologies to solve our clients’ toughest business challenges. You’ll work side-by-side with architects, managers, and engineering consultants to gain a 360-degree perspective of the challenge at hand while contributing your unique perspective to develop innovative solutions.\n\nAbout You\n• You have a customer-first mindset and focus on what is possible versus what is standard practice in the industry.\n• You have excellent product instincts, a passion for great app experiences, a data-centric mindset, and the willingness to do what it takes to have a positive impact on our customers.\n• You can lead projects from concept to delivery by working closely with back-end and front-end developers.\n• You consistently ensure web standards are met and platforms are fully functional before delivery to clients.\n• You have a passion for emerging technologies.\n• You have proven expertise in industry SDLC best practices and delivery excellence.\n• You’re always ready to roll up your sleeves and immerse in the details.\n\nQualifications\n• 5-8+ years of production experience as a developer using JavaScript and TypeScript\n• 2+ years of experience with AWS\n• Excellent hands-on design, coding, testing methodology, and debugging skills\n• Experience with CSS\n• Experience with React.js and/or Angular is highly preferred\n\nAdditional Information\n\nAll your information will be kept confidential according to EEO guidelines.\n\nTexas state base compensation range: $125,000 - 140,000, dependent on experience.\n\nAbout Logic20/20\n\nTo learn more about Logic20/20, please visit: https://www.logic2020.com/careers/life-at-logic\n\nCore Values\n\nAt Logic20/20, we are guided by three core values: Drive toward Excellence, Act with Integrity & Foster a Culture of We. These values were generated and agreed upon by our employees—and they help us pursue our goal of being one of the best companies to work for and to work with. Learn more at https://www.logic2020.com/company/our-values.\n\nLogic20/20 Benefits\n\nWhy Logic20/20? It’s our goal to be one of the best companies to work for. One piece of the puzzle is an evolving set of benefits that extend past medical, dental, and 401(k).\n\nYou will have\n• PTO & Paid Holidays – Worry-free time off to recharge and pursue your personal goals\n• Community & Committees – As part of our “Culture of We,” Logic20/20 invests in providing many social, interest, and learning opportunities\n• Referral Programs & Bonuses – Employee, project, and sales referral programs with paid incentives\n\nEqual Opportunity Statement\n\nWe believe that people should be celebrated: for their talents, ideas, and skills, but most of all, for what makes them unique. We prohibit harassment and/or discrimination based on age, race, creed, color, religion, sex, national origin, ancestry, disability status, veteran status, sexual orientation, gender identity or expression, genetic information, marital status, citizenship status, or any other basis as protected by federal, state, or local law.\n\nTo learn more about our DE&I initiatives, please visit: https://www.logic2020.com/company/diversity-equity-inclusion\n\nPrivacy Policy\n\nDuring the recruitment and hiring process, we gather, process, and store some of your personal data. We consider data privacy a priority. For further information, please view our company privacy policy.",
    job_is_remote: false,
    job_posted_at_timestamp: 1698969600,
    job_posted_at_datetime_utc: "2023-11-03T00:00:00.000Z",
    job_city: "Austin",
    job_state: "TX",
    job_country: "US",
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_benefits: [
      "paid_time_off",
      "retirement_savings",
      "dental_coverage",
      "health_insurance",
    ],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=javascript&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=javascript&htidocid=LmA80Ixex5j6B_DCAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-12-03T22:18:20.000Z",
    job_offer_expiration_timestamp: 1701641900,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "You have a customer-first mindset and focus on what is possible versus what is standard practice in the industry",
        "You have excellent product instincts, a passion for great app experiences, a data-centric mindset, and the willingness to do what it takes to have a positive impact on our customers",
        "You can lead projects from concept to delivery by working closely with back-end and front-end developers",
        "You consistently ensure web standards are met and platforms are fully functional before delivery to clients",
        "You have a passion for emerging technologies",
        "You have proven expertise in industry SDLC best practices and delivery excellence",
        "You’re always ready to roll up your sleeves and immerse in the details",
        "5-8+ years of production experience as a developer using JavaScript and TypeScript",
        "2+ years of experience with AWS",
        "Excellent hands-on design, coding, testing methodology, and debugging skills",
        "Experience with CSS",
      ],
      Responsibilities: [
        "As a JavaScript Developer, you’ll be responsible for all aspects of the software development lifecycle, which includes estimating, technical design, implementation, documentation, testing, deployment, and support of innovative applications developed for our clients",
        "You will team with solution architects and developers on the translation of wireframes and creative designs into functional requirements, and subsequently into technical design",
      ],
      Benefits: [
        "Texas state base compensation range: $125,000 - 140,000, dependent on experience",
        "PTO & Paid Holidays – Worry-free time off to recharge and pursue your personal goals",
        "Community & Committees – As part of our “Culture of We,” Logic20/20 invests in providing many social, interest, and learning opportunities",
        "Referral Programs & Bonuses – Employee, project, and sales referral programs with paid incentives",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    id: 858475,
  },
  {
    employer_name: "BridgeView",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_OK2DY7cxqzfU5YUp7mJLQ6lvG5-0sWJetc3W&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "BridgeView",
    job_id: "ILzHryPg_PDm2ZETAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "JavaScript Developer",
    job_apply_link: "https://www.bridgeviewit.com/jobs/javascript-developer/",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.7494,
    apply_options: [
      {
        publisher: "BridgeView",
        apply_link: "https://www.bridgeviewit.com/jobs/javascript-developer/",
        is_direct: true,
      },
      {
        publisher: "StartWire",
        apply_link:
          "https://www.startwire.com/jobs/denver-co/javascript-developer-4378084284?source=seo",
        is_direct: false,
      },
    ],
    job_description:
      "Bridgeview is currently seeking a JavaScript Developer for a contract-based project. If you love building and supporting technology solutions that make businesses successful, then read on for more details.\n\nTITLE: JavaScript Developer\n\nLOCATION: Denver, CO (Hybrid)\n\nBENEFITS & PERKS: Medical, Dental & Vision on your first day, 4% match on 401(k), Life Insurance, Short & Long-Term Disability, employee perks, and more (detailed below).\n\nOVERVIEW\n\nThe JavaScript Developer will work with a small team of software engineers to harden and develop new features for an AI based software solution. This role focuses on working with technologies such as HTML, CSS, JavaScript, and utilizing Ionic products like Stencil and Capacitor to create high-quality, custom software solutions. As a JavaScript Developer, you will play a crucial role in ensuring the functionality, performance, and user experience.\n\nHOW YOU WILL MAKE AN IMPACT\n• Develop and maintain the front-end components of custom software applications using HTML, CSS, and JavaScript\n• Ionic Products Integration: Leverage Ionic products, such as Stencil and Capacitor, to create cross-platform mobile and web applications\n• Ensure the quality and reliability of software by thoroughly testing features and functionality against project requirements\n• Verify that the software functions correctly on various web browsers and platforms, addressing any compatibility issues\n• Document defects, enhancements, and testing results, and collaborate with developers to resolve issues effectively\n• Evaluate and provide feedback on the user interface and user experience to enhance the overall design and usability\n• Identify and address performance bottlenecks and recommend improvements to enhance application speed and responsiveness\n• Work closely with cross-functional teams, including QA, back-end developers, and project managers, to ensure the successful development and testing of software solutions\n\nEXPERIENCE REQUIRED\n• 2+ years experience as a JavaScript Developer, particularly with HTML, CSS, and React\n• Familiarity with Ionic products, including Stencil and Capacitor\n• Strong understanding of web development best practices and cross-browser compatibility\n• Attention to detail and a commitment to delivering high-quality software\n• Effective communication skills and the ability to collaborate within a team environment\n• Strong problem-solving and troubleshooting skills\n\nPREFERRED EXPERIENCE\n• Experience working for a start-up or ML/AI projects\n• Bachelor's Degree in a related field\n\nBENEFITS\n\nBridgeView makes it easy to say “yes” to joining our team, with national Medical, Dental, Vision, and Life Insurance coverage effective on your very first day. Our 401(k) is 4% matched and fully vested, and we offer voluntary benefits such as TelaDoc, Short & Long-Term Disability, Critical Illness, Accident, AD&D, Legal Shield, etc. We help you take care of your mind with a paid subscription to the Calm app, and your wallet with cashback available through thousands of vendors (Ace Hardware, Verizon, Overstock.com, and more).\n\nABOUT BRIDGEVIEW\n\nBridgeView is a talent and technology consulting company that helps business leaders build exceptional technology teams and deliver complex projects with confidence.\n\nSince 2005, BridgeView's tenured recruiting team has built a vast network of niche technologists and executive leadership candidates to help our clients solve their most complex talent challenges. Paired with strategic consulting services, BridgeView further delivers project collaboration in the areas of people, process, and technology.\n\nThis blended approach allows clients to adjust in real-time to align with their budgets while receiving Big 5 expertise to meet their objectives.\n\nBridgeView. Within Sight.\n\nWe are an equal opportunity employer and value diversity. All employment decisions are made due to qualifications, merit, and business need. The successful candidate’s starting salary will be determined based on permissible, non-discriminatory factors such as skills, experience, and geographic location.",
    job_is_remote: false,
    job_posted_at_timestamp: 1698770481,
    job_posted_at_datetime_utc: "2023-10-31T16:41:21.000Z",
    job_city: "Denver",
    job_state: "CO",
    job_country: "US",
    job_latitude: 39.739235,
    job_longitude: -104.99025,
    job_benefits: ["dental_coverage", "retirement_savings", "health_insurance"],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=javascript&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=javascript&htidocid=ILzHryPg_PDm2ZETAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-10-31T16:41:21.000Z",
    job_offer_expiration_timestamp: 1730392881,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 24,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 55,
    job_max_salary: 63,
    job_salary_currency: "USD",
    job_salary_period: "HOUR",
    job_highlights: {
      Qualifications: [
        "2+ years experience as a JavaScript Developer, particularly with HTML, CSS, and React",
        "Familiarity with Ionic products, including Stencil and Capacitor",
        "Strong understanding of web development best practices and cross-browser compatibility",
        "Attention to detail and a commitment to delivering high-quality software",
        "Effective communication skills and the ability to collaborate within a team environment",
        "Strong problem-solving and troubleshooting skills",
      ],
      Responsibilities: [
        "The JavaScript Developer will work with a small team of software engineers to harden and develop new features for an AI based software solution",
        "This role focuses on working with technologies such as HTML, CSS, JavaScript, and utilizing Ionic products like Stencil and Capacitor to create high-quality, custom software solutions",
        "As a JavaScript Developer, you will play a crucial role in ensuring the functionality, performance, and user experience",
        "Develop and maintain the front-end components of custom software applications using HTML, CSS, and JavaScript",
        "Ionic Products Integration: Leverage Ionic products, such as Stencil and Capacitor, to create cross-platform mobile and web applications",
        "Ensure the quality and reliability of software by thoroughly testing features and functionality against project requirements",
        "Verify that the software functions correctly on various web browsers and platforms, addressing any compatibility issues",
        "Document defects, enhancements, and testing results, and collaborate with developers to resolve issues effectively",
        "Evaluate and provide feedback on the user interface and user experience to enhance the overall design and usability",
        "Identify and address performance bottlenecks and recommend improvements to enhance application speed and responsiveness",
        "Work closely with cross-functional teams, including QA, back-end developers, and project managers, to ensure the successful development and testing of software solutions",
      ],
      Benefits: [
        "BENEFITS & PERKS: Medical, Dental & Vision on your first day, 4% match on 401(k), Life Insurance, Short & Long-Term Disability, employee perks, and more (detailed below)",
        "BridgeView makes it easy to say “yes” to joining our team, with national Medical, Dental, Vision, and Life Insurance coverage effective on your very first day",
        "Our 401(k) is 4% matched and fully vested, and we offer voluntary benefits such as TelaDoc, Short & Long-Term Disability, Critical Illness, Accident, AD&D, Legal Shield, etc",
        "We help you take care of your mind with a paid subscription to the Calm app, and your wallet with cashback available through thousands of vendors (Ace Hardware, Verizon, Overstock.com, and more)",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_occupational_categories: ["Developer - JavaScript"],
    id: 697638,
  },
  {
    employer_name: "Upwork",
    employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
    employer_website: "http://www.elance.com",
    employer_company_type: "Computer Services",
    job_publisher: "Upwork",
    job_id: "sHIkJ4hyBl0E5cyoAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "Web Developer - Shopify / Liquid / JavaScript",
    job_apply_link:
      "https://www.upwork.com/freelance-jobs/apply/Web-Developer-Shopify-Liquid-JavaScript_~0113ced75c03e884c1/",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.687,
    apply_options: [
      {
        publisher: "Upwork",
        apply_link:
          "https://www.upwork.com/freelance-jobs/apply/Web-Developer-Shopify-Liquid-JavaScript_~0113ced75c03e884c1/",
        is_direct: true,
      },
    ],
    job_description:
      "We are growing and looking for a talented Full Stack Developer with a keen eye for design and a passion for creating seamless online retail solutions within the Shopify environment.\n\nResponsibilities:\n\n- Develop, test, and implement new features and functionalities within the Shopify platform.\n\n- Customize existing Shopify theme to meet branding and business requirements.\n\n- Write clean, maintainable, and efficient code in Shopify Liquid, HTML, CSS, and JavaScript.\n\n- Ensure cross-browser and cross-platform compatibility.\n\n- Collaborate with UX/UI designers to translate visual concepts into functional online experiences.\n\n- Optimize application for maximum speed and scalability.\n\nSkills and Qualifications:\n\n- Proficiency in English or German (written and verbal).\n\n- In-depth experience with Shopify's theming system and Liquid templating.\n\n- Strong knowledge of HTML, CSS, and JavaScript.\n\n- Understanding of web design principles and best practices.\n\n- Experience with responsive and adaptive design.\n\n- Good understanding of SEO principles and ensuring that applications will adhere to them.\n\n- Excellent problem-solving skills and attention to detail.\n\n- Ability to work independently as well as part of a collaborative team.\n\nPlease send your application to us within Upwork. Include a short introduction of yourself and a portfolio showcasing your previous work.",
    job_is_remote: true,
    job_posted_at_timestamp: 1699112747,
    job_posted_at_datetime_utc: "2023-11-04T15:45:47.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=javascript&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=javascript&htidocid=sHIkJ4hyBl0E5cyoAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: [
      "JavaScript",
      "Shopify",
      "HTML",
      "Web Development",
      "CSS",
    ],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 25,
    job_max_salary: 45,
    job_salary_currency: "USD",
    job_salary_period: "HOUR",
    job_highlights: {
      Qualifications: [
        "Proficiency in English or German (written and verbal)",
        "In-depth experience with Shopify's theming system and Liquid templating",
        "Strong knowledge of HTML, CSS, and JavaScript",
        "Understanding of web design principles and best practices",
        "Experience with responsive and adaptive design",
        "Good understanding of SEO principles and ensuring that applications will adhere to them",
        "Excellent problem-solving skills and attention to detail",
        "Ability to work independently as well as part of a collaborative team",
      ],
      Responsibilities: [
        "Develop, test, and implement new features and functionalities within the Shopify platform",
        "Customize existing Shopify theme to meet branding and business requirements",
        "Write clean, maintainable, and efficient code in Shopify Liquid, HTML, CSS, and JavaScript",
        "Ensure cross-browser and cross-platform compatibility",
        "Collaborate with UX/UI designers to translate visual concepts into functional online experiences",
        "Optimize application for maximum speed and scalability",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_naics_code: "541511",
    job_naics_name: "Custom Computer Programming Services",
    id: 316496,
  },
  {
    employer_name: "American Express",
    employer_logo:
      "https://upload.wikimedia.org/wikipedia/commons/f/fa/American_Express_logo_%282018%29.svg",
    employer_website: "http://www.americanexpress.com",
    employer_company_type: "Retail",
    job_publisher: "Trabajo.org",
    job_id: "cgwjmTHOG_p_SN1gAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "JavaScript Engineer",
    job_apply_link:
      "https://us.trabajo.org/job-835-20231104-3903c8f201944f81a68f4233a0b60a37",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.4713,
    apply_options: [
      {
        publisher: "Trabajo.org",
        apply_link:
          "https://us.trabajo.org/job-835-20231104-3903c8f201944f81a68f4233a0b60a37",
        is_direct: false,
      },
    ],
    job_description:
      "• *Description**\n• *You Lead the Way. We’ve Got Your Back.**\nAt American Express, we know that with the right backing, people and businesses have the power to progress in incredible ways. Whether we’re supporting our customers’ financial confidence to move ahead, taking commerce to new heights, or encouraging people to explore the world, our colleagues are constantly redefining what’s possible — and we’re proud to back each other every step of the way. When you join #TeamAmex, you become part of a diverse community of over 60,000 colleagues, all with a common goal to deliver an exceptional customer experience every day. We back our colleagues with the support they need to thrive, professionally and personally. That’s why we have Amex Flex, our enterprise working model that provides greater flexibility to colleagues while ensuring we preserve the important aspects of our unique in-person culture. Depending on role and business needs, colleagues will either work onsite, in a hybrid model (combination of in-office and virtual days) or fully virtually.\nIn building leading edge real-time processing platforms, you will be transforming our iconic, global brand. As a part of our technology team, you will collaborate to bring ground-breaking and diverse ideas to life that power the digital systems, services, products, and platforms upon which millions of customers around the world depend. If you love to build user interfaces that empower customers and use the latest technologies, we’ll support you with an open environment and learning culture to grow your career.\n• *Focus:**\nDesign, develop, solve problem, debug, evaluate, modify, deploy, and document web front end software and systems that meet the needs of customer-facing applications, business applications, and/or internal end user applications.\n• *Organizational Context:**\nA member of a product engineering team reporting to an Engineering Director.\n• *How will you make an impact in this role?**\nSoftware Development\n+ Function as member of an agile team by contributing to software builds through consistent development practices (tools, common components, and documentation).\n+ Participate in code reviews and automated testing.\n+ Debug basic software components and identify code defects for remediation.\n+ Enable the deployment, support, and monitoring of software across development, test, integration, and production environments.\n+ Automate deployments.\n+ Automatically scale applications based on demand.\nLeadership\n+ Demonstrate increased self-reliance to achieve team goals.\n+ Influence team members with creative changes and improvements by challenging the status quo and demonstrating risk taking.\nIn order to work in or visit any of our offices in the United States, we require colleagues to be fully vaccinated against COVID-19.\n• *Qualifications**\nAt least 4 years of software development experience in a professional environment and/or comparable experience such as:\n+ Proficiency in JavaScript and CSS, including DOM manipulation and the JavaScript object model.\n+ Deep understanding of and experience with React.js, its core principles, and popular workflows (such as Flux or Redux).\n+ Familiarity with newer specifications of EcmaScript.\n+ Expertise in JSON Schema.\n+ Experience with data structure libraries.\n+ Experience with both Responsive and Adaptive Web Design.\n+ Familiar with Agile or other rapid application development methods.\n+ Familiarity with modern front and back-end build pipelines and tools.\n+ Strong focus on writing automated tests for your own code.\n+ Ability to perform benchmarking and optimization.\n+ Bachelor’s Degree in computer science, computer science engineering, or related experience required; advanced degree preferred.\n• *High Performance Behaviors:**\n+ Recognizes opportunities to adopt innovative technologies to enable business capabilities.\n+ Keeps up to date on current research and technology in the industry.\n+ Recognizes the importance of collaboration to achieve objectives.\n+ Clearly communicates ideas and concepts to others.\n+ Finds opportunities within projects and acts on own initiative without being prompted, including making appropriate decisions as vital.\n+ Provides feedback to team members in code reviews.\n+ Drive creative changes & continuous improvements.\n+ Mentors and guides junior team members to success within the team.\n+ Excellent written and verbal communication skills in the English language.\nEmployment eligibility to work with American Express in the U.S. is required as the company will not pursue visa sponsorship for these positions.\nAmerican Express is an equal opportunity employer and makes employment decisions without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, protected veteran status, disability status, age, or any other status protected by law.\n• *Job:** Technology\n• *Primary Location:** United States\n• *Schedule** Full-time\n• *Req ID:** 22000154",
    job_is_remote: false,
    job_posted_at_timestamp: 1699115123,
    job_posted_at_datetime_utc: "2023-11-04T16:25:23.000Z",
    job_city: "Hartford",
    job_state: "CT",
    job_country: "US",
    job_latitude: 41.765804,
    job_longitude: -72.67337,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=javascript&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=javascript&htidocid=cgwjmTHOG_p_SN1gAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-11-11T00:00:00.000Z",
    job_offer_expiration_timestamp: 1699660800,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 48,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "At least 4 years of software development experience in a professional environment and/or comparable experience such as:",
        "Proficiency in JavaScript and CSS, including DOM manipulation and the JavaScript object model",
        "Deep understanding of and experience with React.js, its core principles, and popular workflows (such as Flux or Redux)",
        "Familiarity with newer specifications of EcmaScript",
        "Expertise in JSON Schema",
        "Experience with data structure libraries",
        "Experience with both Responsive and Adaptive Web Design",
        "Familiar with Agile or other rapid application development methods",
        "Familiarity with modern front and back-end build pipelines and tools",
        "Strong focus on writing automated tests for your own code",
        "Ability to perform benchmarking and optimization",
        "*High Performance Behaviors:**",
        "Recognizes opportunities to adopt innovative technologies to enable business capabilities",
        "Keeps up to date on current research and technology in the industry",
        "Recognizes the importance of collaboration to achieve objectives",
        "Clearly communicates ideas and concepts to others",
        "Finds opportunities within projects and acts on own initiative without being prompted, including making appropriate decisions as vital",
        "Mentors and guides junior team members to success within the team",
        "Excellent written and verbal communication skills in the English language",
        "Employment eligibility to work with American Express in the U.S. is required as the company will not pursue visa sponsorship for these positions",
      ],
      Responsibilities: [
        "Design, develop, solve problem, debug, evaluate, modify, deploy, and document web front end software and systems that meet the needs of customer-facing applications, business applications, and/or internal end user applications",
        "*Organizational Context:**",
        "Function as member of an agile team by contributing to software builds through consistent development practices (tools, common components, and documentation)",
        "Participate in code reviews and automated testing",
        "Debug basic software components and identify code defects for remediation",
        "Enable the deployment, support, and monitoring of software across development, test, integration, and production environments",
        "Automate deployments",
        "Demonstrate increased self-reliance to achieve team goals",
        "Influence team members with creative changes and improvements by challenging the status quo and demonstrating risk taking",
        "Drive creative changes & continuous improvements",
      ],
    },
    job_job_title: "Javascript engineer",
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_naics_code: "454111",
    job_naics_name: "Electronic Shopping",
    id: 163977,
  },
  {
    employer_name: "firstPRO 360",
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: "Geebo",
    job_id: "TONyCh5irKmupDzQAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Web Developer (Javascript)",
    job_apply_link:
      "https://geebo.com/jobs-online/view/id/678250191-web-developer-javascript-/",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.4587,
    apply_options: [
      {
        publisher: "Geebo",
        apply_link:
          "https://geebo.com/jobs-online/view/id/678250191-web-developer-javascript-/",
        is_direct: true,
      },
    ],
    job_description:
      "W2 Candidates only - Client cannot sponsor visa's Growing and stable company has an immediate need for a mid to senior-level Web Developer on a direct hire basis.\nThis company values a generalist more than a person who is an expert in one technology.\nIn this role, you will work on a smart and passionate team, developing and maintaining apps that tie in directly with the company's business.\nYour work is critical to the growth and well-being of the business.\nYou must have solid Javascript and Angular experience and you work must have been focused on the front end as a whole.\nOne of the first big projects you will work on will involve HTML, CSS, and Javascript only.\nC# exposure is a huge benefit for them as well.\nThey are looking for a Developer that enjoys coding, solving complex problems, and enjoys staying up-to-date with the latest trends.\nThis is a top company to work for, and they offer competitive salaries, work from home a day a week, and 401K matching.\nDevelop web apps and tools for users inside and outside the company.\nImprove on exiting product; fix defects as needed.\nAssist with upgrading to new tech as needed.\nHandle documentation as new products are built.\nRequirements :\nBachelor's Degree strongly preferred.\n5\nyears of web development experience - strong Javascript, Angular, HTML5, CSS, Git/Subversion, understands how everything ties to SQL Server.\nEnjoys staying up-to-date with trends, particularly Javascript Frameworks.\nC# ASP.\nNet exposure strongly preferred.\nWrites clean code and has a solid understanding of principles.\nPreferences:\nAngular2 (company has it in Beta right now);Typescript; Agile dev methodology; High avail systems experience.\nIf you are interested in this opportunity, please email your resume to a.\npiede@firstpro360.\ncom.\nEstimated Salary: $20 to $28 per hour based on qualifications.",
    job_is_remote: false,
    job_posted_at_timestamp: 1698969600,
    job_posted_at_datetime_utc: "2023-11-03T00:00:00.000Z",
    job_city: "Norcross",
    job_state: "GA",
    job_country: "US",
    job_latitude: 33.94111,
    job_longitude: -84.213745,
    job_benefits: ["retirement_savings"],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=javascript&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=javascript&htidocid=TONyCh5irKmupDzQAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-11-10T00:00:00.000Z",
    job_offer_expiration_timestamp: 1699574400,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 20,
    job_max_salary: 28,
    job_salary_currency: "USD",
    job_salary_period: "HOUR",
    job_highlights: {
      Qualifications: [
        "You must have solid Javascript and Angular experience and you work must have been focused on the front end as a whole",
        "They are looking for a Developer that enjoys coding, solving complex problems, and enjoys staying up-to-date with the latest trends",
        "years of web development experience - strong Javascript, Angular, HTML5, CSS, Git/Subversion, understands how everything ties to SQL Server",
        "Enjoys staying up-to-date with trends, particularly Javascript Frameworks",
        "Writes clean code and has a solid understanding of principles",
        "Angular2 (company has it in Beta right now);Typescript; Agile dev methodology; High avail systems experience",
      ],
      Responsibilities: [
        "Develop web apps and tools for users inside and outside the company",
        "Improve on exiting product; fix defects as needed",
        "Assist with upgrading to new tech as needed",
        "Handle documentation as new products are built",
      ],
      Benefits: [
        "This is a top company to work for, and they offer competitive salaries, work from home a day a week, and 401K matching",
        "Estimated Salary: $20 to $28 per hour based on qualifications",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    id: 227316,
  },
  {
    employer_name: "SA Technologies Inc",
    employer_logo: null,
    employer_website: "http://www.satechglobal.com",
    employer_company_type: null,
    job_publisher: "Jobrapido.com",
    job_id: "39d5BwpaYufDteXcAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Front End JavaScript Developer",
    job_apply_link: "https://us.jobrapido.com/jobpreview/3070961079",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.4244,
    apply_options: [
      {
        publisher: "Jobrapido.com",
        apply_link: "https://us.jobrapido.com/jobpreview/3070961079",
        is_direct: false,
      },
    ],
    job_description:
      "A company is looking for a Front End JS Developer.\nKey Responsibilities:\n\nStrong proficiency in Javascript with Nextjs or React\nExperience with Vercel/Cloudflare AI stack\nKnowledge of third party JS Integrations (plaid, supabase, stripe, auth etc)\n\nQualifications:\n\n6-12 years of experience as a Software Engineer-Front End JS Developer\nExperience with Python/Go api or backend development\nExperience with UI/UX design, particularly in reading Figma",
    job_is_remote: false,
    job_posted_at_timestamp: 1698710400,
    job_posted_at_datetime_utc: "2023-10-31T00:00:00.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=javascript&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=javascript&htidocid=39d5BwpaYufDteXcAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 72,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Strong proficiency in Javascript with Nextjs or React",
        "Experience with Vercel/Cloudflare AI stack",
        "Knowledge of third party JS Integrations (plaid, supabase, stripe, auth etc)",
        "6-12 years of experience as a Software Engineer-Front End JS Developer",
        "Experience with Python/Go api or backend development",
        "Experience with UI/UX design, particularly in reading Figma",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    id: 923406,
  },
  {
    employer_name: "Upwork",
    employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
    employer_website: "http://www.elance.com",
    employer_company_type: "Computer Services",
    job_publisher: "Upwork",
    job_id: "Nun1-soTwcfS8sKsAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "JavaScript",
    job_apply_link:
      "https://www.upwork.com/freelance-jobs/apply/JavaScript_~0187156a0f3feebc03/",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.687,
    apply_options: [
      {
        publisher: "Upwork",
        apply_link:
          "https://www.upwork.com/freelance-jobs/apply/JavaScript_~0187156a0f3feebc03/",
        is_direct: true,
      },
    ],
    job_description:
      "I am building an IoT app that requires javaScipt language.\n\nI have wireless devices with me and the work will be remote since I have the devices. Preferably candidates who have knowledge in wireless sensors, such as double sided two-way ranging. I am trying to solve an issue to broadcast time and achieve time synchronization between devices using DS-TWR.",
    job_is_remote: true,
    job_posted_at_timestamp: 1698943710,
    job_posted_at_datetime_utc: "2023-11-02T16:48:30.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=javascript&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=javascript&htidocid=Nun1-soTwcfS8sKsAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: ["JavaScript", "Python"],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Preferably candidates who have knowledge in wireless sensors, such as double sided two-way ranging",
        "I am trying to solve an issue to broadcast time and achieve time synchronization between devices using DS-TWR",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_naics_code: "541511",
    job_naics_name: "Custom Computer Programming Services",
    id: 751962,
  },
  {
    employer_name: "Open Systems Technologies",
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: "ZipRecruiter",
    job_id: "U3cIBazZlso9evehAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "HTML/JavaScript Programmer",
    job_apply_link:
      "https://www.ziprecruiter.com/c/Open-Systems-Technologies/Job/HTML-JavaScript-Programmer/-in-New-York,NY?jid=ef197b31d5d7e266",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6747,
    apply_options: [
      {
        publisher: "ZipRecruiter",
        apply_link:
          "https://www.ziprecruiter.com/c/Open-Systems-Technologies/Job/HTML-JavaScript-Programmer/-in-New-York,NY?jid=ef197b31d5d7e266",
        is_direct: false,
      },
      {
        publisher: "SmartRecruiters Job Search",
        apply_link:
          "https://jobs.smartrecruiters.com/OpenSystemsTechnologies/743999655369433-html-javascript-programmer",
        is_direct: false,
      },
    ],
    job_description:
      "Company Description\n\nOpen Systems Technologies is a national provider of smeart staffing solutions, providing contract staffing, permanent placements and executive searches in the following skill areas:\n\n- Technology\n\n- Finance, Accounting, and Operations\n\n- Government Services\n\n- Legal\n\n- Global Services\n\nEstablished in New York in 1990, Open Systems Technologies is one of the largest, privately held, staffing companies in the world. We have experienced organic growth over the past 25 years and currently employ over 1,500 consultants in 16 domestic and international markets. Through our brands of Open Systems, OST Financial, OST Legal, OST Government Services, and OST Global we strive for continued expansion and excellence in the staffing industry. With the Global Services division, starting Jan-2012, Open Systems has expanded into the ITO & BPO Projects/Solutions business.\n\nJob Description\n\nResponsibilities\n• Architect and define presentation layer framework to solve complex designs\n• Create all coded Presentation Layer deliverables. Establish presentation layer requirements\n• Develop server side components that interacts with presentation layer\n• Rapidly produce interim deliverables (such as style guide components, technical specifications, browser and market analysis, hi-fidelity prototypes as proofs of concept, etc.) in addition to the final live site or application\n• Take initiative to research and learn emerging technologies\n• Demos of completed software to the business\n\nSkills:\n• Architecting and designing high performance web application.\n• 5+ years experience hand-coding HTML, D/XHTML, JavaScript, CSS 2 & 3, JSP\n• 7+ years experience using J2EE to develop dynamic web applications\n• Expertise developing and testing across multiple browsers, platforms, DOM implementations\n• Experience with JSON, usages of JavaScript statements such as switch, case, throw, closures, and working knowledge of WebKit\n• Experience with Rich Internet Applications, AJAX, particularly technical and coding aspects such as Object Oriented JavaScript, etc. required.\n• User Interface Design, Information Architecture, graphic design experience a plus\n• Understanding of good design principles and ability to adhere to complex design\n• Extensive hand-coding expertise in HTML 4 & 5, D/XHTML, J2EE, JavaScript, CSS 2 & 3, jQuery, Webcomponents, ReactJS\n• Expert level of hand-coding experience in Core JavaScript and JSON\n• Experience working in Agile development environment, scrums meeting, and rapid prototyping\n• Bachelors or Masters degree in Computer Science, Information Science or related technical or quantitative discipline\n\nAdditional Information\n\nAll your information will be kept confidential according to EEO guidelines.",
    job_is_remote: false,
    job_posted_at_timestamp: 1499670000,
    job_posted_at_datetime_utc: "2017-07-10T07:00:00.000Z",
    job_city: "New York",
    job_state: "NY",
    job_country: "US",
    job_latitude: 40.712776,
    job_longitude: -74.005974,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=javascript&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=javascript&htidocid=U3cIBazZlso9evehAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-12-04T00:00:00.000Z",
    job_offer_expiration_timestamp: 1701648000,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Architecting and designing high performance web application",
        "5+ years experience hand-coding HTML, D/XHTML, JavaScript, CSS 2 & 3, JSP",
        "7+ years experience using J2EE to develop dynamic web applications",
        "Expertise developing and testing across multiple browsers, platforms, DOM implementations",
        "Experience with JSON, usages of JavaScript statements such as switch, case, throw, closures, and working knowledge of WebKit",
        "Experience with Rich Internet Applications, AJAX, particularly technical and coding aspects such as Object Oriented JavaScript, etc. required",
        "Understanding of good design principles and ability to adhere to complex design",
        "Extensive hand-coding expertise in HTML 4 & 5, D/XHTML, J2EE, JavaScript, CSS 2 & 3, jQuery, Webcomponents, ReactJS",
        "Expert level of hand-coding experience in Core JavaScript and JSON",
        "Experience working in Agile development environment, scrums meeting, and rapid prototyping",
        "Bachelors or Masters degree in Computer Science, Information Science or related technical or quantitative discipline",
      ],
      Responsibilities: [
        "Architect and define presentation layer framework to solve complex designs",
        "Create all coded Presentation Layer deliverables",
        "Establish presentation layer requirements",
        "Develop server side components that interacts with presentation layer",
        "Rapidly produce interim deliverables (such as style guide components, technical specifications, browser and market analysis, hi-fidelity prototypes as proofs of concept, etc.) in addition to the final live site or application",
        "Take initiative to research and learn emerging technologies",
        "Demos of completed software to the business",
      ],
    },
    job_job_title: "Programmer",
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_occupational_categories: ["15-1134.00: Web Developers"],
    id: 630279,
  },
  {
    employer_name: "Cisco",
    employer_logo: "https://www.cisco.com/web/fw/i/logo-open-graph.gif",
    employer_website: "http://www.cisco.com",
    employer_company_type: "Manufacturing",
    job_publisher: "Chegg Internships",
    job_id: "27Im6_iTQ3dV-qcvAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "JavaScript Application Developers",
    job_apply_link: "https://www.internships.com/posting/lit_39570842807",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5854,
    apply_options: [
      {
        publisher: "Chegg Internships",
        apply_link: "https://www.internships.com/posting/lit_39570842807",
        is_direct: false,
      },
    ],
    job_description:
      "Job Title\n\nSoftware Engineer\n\nJob Location\n\nCisco\n\nJob Overview\n\nWe are looking for a highly motivated Software Engineer to join our team in Cisco IT Products. You will be responsible for supporting, administering, and developing applications and services for engineering. This is a great opportunity to work with a diversified team and provide web application development services and support.\n\nCompensation\n\nDOE (Depends on Experience)\n\nResponsibilities\n• Write design specifications and functional specifications.\n• Provide support to local internal clients and assist in the support of systems at other locations.\n• Follow standard design and implementation processes and procedures.\n• Develop well-defined software modules.\n• Perform well-defined unit, product level integration, and development tests.\n• Write portions of test plans.\n• Debug sections of the subsystem.\n• Work closely with diverse peer engineers at other locations such as San Jose, CA; Research Triangle Park, NC.\n\nRequirements\n• 6-8+ years of experience in developing web-based applications using Java, J2EE, Perl, JavaScript, HTML.\n• Strong relational database and SQL skills.\n• Strong object-oriented analysis and design skills.\n• Good customer service skills.\n• Must be creative and able to develop new simple approaches to complex design problems.\n• Ability to handle multiple concurrent activities and have a flexible, positive attitude.\n• Must work well with team members, acting as a mentor to other engineers, helping to motivate and solve problems.\n• Excellent written and verbal communication skills.\n• Strong organizational skills.\n• High energy and a real passion for your work.\n\nWe're excited for you to apply!",
    job_is_remote: false,
    job_posted_at_timestamp: 1694563200,
    job_posted_at_datetime_utc: "2023-09-13T00:00:00.000Z",
    job_city: "San Jose",
    job_state: "CA",
    job_country: "US",
    job_latitude: 37.33874,
    job_longitude: -121.885254,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=javascript&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=javascript&htidocid=27Im6_iTQ3dV-qcvAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 72,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "6-8+ years of experience in developing web-based applications using Java, J2EE, Perl, JavaScript, HTML",
        "Strong relational database and SQL skills",
        "Strong object-oriented analysis and design skills",
        "Good customer service skills",
        "Must be creative and able to develop new simple approaches to complex design problems",
        "Ability to handle multiple concurrent activities and have a flexible, positive attitude",
        "Must work well with team members, acting as a mentor to other engineers, helping to motivate and solve problems",
        "Excellent written and verbal communication skills",
        "Strong organizational skills",
        "High energy and a real passion for your work",
      ],
      Responsibilities: [
        "You will be responsible for supporting, administering, and developing applications and services for engineering",
        "This is a great opportunity to work with a diversified team and provide web application development services and support",
        "Write design specifications and functional specifications",
        "Provide support to local internal clients and assist in the support of systems at other locations",
        "Follow standard design and implementation processes and procedures",
        "Develop well-defined software modules",
        "Perform well-defined unit, product level integration, and development tests",
        "Write portions of test plans",
        "Debug sections of the subsystem",
        "Work closely with diverse peer engineers at other locations such as San Jose, CA; Research Triangle Park, NC",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_naics_code: "3342",
    job_naics_name: "Communications Equipment Manufacturing",
    id: 987220,
  },
  {
    employer_name: "Atechstar",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPd-hps7yHu6ZmQPwa8QzKacpqKLbzwCNNoBVY&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "OPTnation",
    job_id: "oC7o85knOvOipcJRAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Javascript Developer",
    job_apply_link:
      "https://www.optnation.com/javascript-developer-job-in-new-york-ny-view-jobid-32880",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6752,
    apply_options: [
      {
        publisher: "OPTnation",
        apply_link:
          "https://www.optnation.com/javascript-developer-job-in-new-york-ny-view-jobid-32880",
        is_direct: false,
      },
    ],
    job_description:
      "Requirements Bachelor’s degree in computer science from a top university. 3-5 years experience in technology. Strong Javascript skills. Experience with leading Javascript framework. Familiarity with PHP recommended. Comfort with PHPStorm or Eclipse IDE. Understanding of basic database concepts and SQL. Comfortable with Agile/Scrum SDLC.\n\nKey Skills HTML and CSS. Algorithms and Data Structures. DOM Manipulation. Source Control. Testing/Debugging. How to Choose the Best JavaScript Framework. Web Performance Optimization.",
    job_is_remote: false,
    job_posted_at_timestamp: 1675900800,
    job_posted_at_datetime_utc: "2023-02-09T00:00:00.000Z",
    job_city: "New York",
    job_state: "NY",
    job_country: "US",
    job_latitude: 40.712776,
    job_longitude: -74.005974,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=javascript&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=javascript&htidocid=oC7o85knOvOipcJRAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: ["Web Performance", "Testing", "Debugging."],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 115000,
    job_max_salary: 135000,
    job_salary_currency: "USD",
    job_salary_period: "YEAR",
    job_highlights: {
      Qualifications: [
        "Requirements Bachelor’s degree in computer science from a top university",
        "3-5 years experience in technology",
        "Strong Javascript skills",
        "Experience with leading Javascript framework",
        "Familiarity with PHP recommended",
        "Comfort with PHPStorm or Eclipse IDE",
        "Understanding of basic database concepts and SQL",
        "Comfortable with Agile/Scrum SDLC",
        "Key Skills HTML and CSS",
        "Algorithms and Data Structures",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    id: 856798,
  },
];
